### ISSUE TITLE
Item Infos

### ISSUE THREAD

**Issue by XeDotCom** [Iapetus-11/Villager-Bot#142]
### Feature
- https://github.com/XeDotCom/villager-bot-item-data-program 
- This issue exists cause im dumb af plus i can't code shit

### Reason
- Information 
- note: currently only default mining findables are listed

**Comment by Iapetus-11** [comment]
Doesn't have to be a program, it could be a series of markdown documents that link to each other or use the wiki feature or something.

**Comment by XeDotCom** [comment]
its not a program, its just a json file :/
program symbolizes the joint effort that no one contributed to

**Comment by Iapetus-11** [comment]
*ah*
