### ISSUE TITLE
Proper credit.

### ISSUE THREAD

**Issue by XeDotCom** [Iapetus-11/Villager-Bot#161]
Petus, if you are gonna remove chez and Kaosj from the credits, I'm not stopping you. It's your bot. But removing them from the credits does not take into consideration the work they have put into the bot.

So reinstate their names, or it'll be disrespecting the hours they've put into the bot.

**Comment by Iapetus-11** [comment]
They don't want to be part of the community, yet they still want to be recognized as a part of the community. You can't have it both ways.
