### ISSUE TITLE
what is bypass authorization token ?

### ISSUE THREAD

**Issue by nostorian** [Iapetus-11/Villager-Bot#182]
what is bypass authorization token in your villager api's .env file, and what do i enter in it? i am kinda confused on how to host this api

**Comment by Iapetus-11** [comment]
This isn't an API, this is a bot. The bypass token is currently not used and is optional, its purpose was to tell the API to not ratelimit Villager Bot. If you're talking about the old https://github.com/Iapetus-11/villager-api, it's no longer in use and has been replaced by https://github.com/Iapetus-11/api.iapetus11.me/

**Comment by nostorian** [comment]
oh ok, sorry, i thought the old one was the current one and since it was archived couldnt open my issue, anyways i will open a new issue there, for problems related to the new api
