### ISSUE TITLE
Sup’

### ISSUE THREAD

**Issue by ZeldaMasterhehe** [Iapetus-11/Villager-Bot#197]
My friends are coming.(they r older than me btw) and taller🤦 But stop banning me. I’ll just chat here.

**Comment by ZeldaMasterhehe** [comment]
They r coming to ur server

**Comment by ZeldaMasterhehe** [comment]
To chat about me

**Comment by ZeldaMasterhehe** [comment]
Also I listen to XXXTENTACION

**Comment by quaackk** [comment]
no one asked
