### ISSUE TITLE
The commands are working very slowly 

### ISSUE THREAD

**Issue by SahildsawFF** [Iapetus-11/Villager-Bot#259]
### To Reproduce
1. Type in `!!something`
2. Wait two seconds...
3. ...
4. ...

**Comment by Iapetus-11** [comment]
I cannot help you or resolve the issue without more information.

- Does this issue occur often or is it permanent?
- Is it only for economy commands or is it for all commands?
- What does the `!!ping` command output?
- Is the delay from when you invoke the command always around two seconds?

**Comment by Iapetus-11** [comment]
Closed due to no response
