### ISSUE TITLE
Ensure .env cluster count matches up with that in secrets.json

### ISSUE THREAD

**Issue by Infernum1** [Iapetus-11/Villager-Bot#261]
- Check .env when the bot starts and make sure that the cluster count is the same as in the secret.json files
- Neither Karen nor the clusters should start

**Comment by Iapetus-11** [comment]
I just realized this wouldn't work in the case Villager Bot is distributed across multiple machines. Perhaps we could have a "debug" key in our secrets.jsons which would enable this functionality
